name: Nightly Unstable Build and Package

on:
  schedule:
    - cron: '12 19 * * *'  # Run at 1:00 AM UTC every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  call-unstable-build:
    uses: redis/redis-rpm/.github/workflows/rpm.yml@unstable
